export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const CHANGE_ROWS_PER_PAGE = 'CHANGE_ROWS_PER_PAGE';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CATCH_POKEMON = 'CATCH_POKEMON';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';